a=input()
king,queen,look,bisop,night,phone=a.split(" ")
king=1-int(king)
queen=1-int(queen)
look=2-int(look)
bisop=2-int(bisop)
night=2-int(night)
phone=8-int(phone)
print(king," ",queen," ",look," ",bisop," ",night," ",phone)